apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: github-weather
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: github-weather
            image: docker.io/varankinv/github-weather:v1.0.0
            command: ["/bin/sh", "-c"]
            args: ["/bin/github-weather --debug --github.token $(GITHUB_TOKEN) --owm.api-key $(OPENWEATHER_API_TOKEN) --owm.query Madrid"]
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 100m
                memory: 128Mi
            env:
              - name: GITHUB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: github-weather
                    key: github_token
              - name: OPENWEATHER_API_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: github-weather
                    key: openweather_api_token
          restartPolicy: OnFailure
