apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: github-weather
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: github-weather
            image: docker.io/varankinv/github-weather:v1.0.0
            command: ["/bin/github-weather"]
            args:
              - "--debug"
              - "--configuration"
              - "/secrets/config.yml"
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 100m
                memory: 128Mi
            volumeMounts:
              - name: config-secret-volume
                mountPath: "/secrets/"
                readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: config-secret-volume
              secret:
                secretName: gh-config-secret
