apiVersion: batch/v1
kind: CronJob
metadata:
  name: github-weather
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: github-weather
            image: docker.io/varankinv/github-weather:v3.2.1
            command: ["/bin/github-weather"]
            args:
              - "--debug"
              - "--configuration"
              - "/secrets/config.yaml"
            resources:
              limits:
                memory: 128Mi
              requests:
                cpu: 10m
                memory: 10Mi
            volumeMounts:
              - name: config-secret-volume
                mountPath: "/secrets/"
                readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: config-secret-volume
              secret:
                secretName: github-weather-config
