env:
  - GO111MODULE=on
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
    - arm
    - arm64
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
# dockers:
# - image_templates:
#   - 'docker.io/varankinv/github-weather:{{ .Tag }}'
#   - 'docker.io/varankinv/github-weather:latest'
#   dockerfile: Dockerfile
#   binaries:
#     - github-weather
